// Auto-generated by exotic-car-logos-updater — do not edit manually
import abarth from "./logos/abarth.png";
import alfaRomeo from "./logos/alfa-romeo.png";
import deTomaso from "./logos/de-tomaso.png";
import ferrari from "./logos/ferrari.png";
import lamborghini from "./logos/lamborghini.png";
import maserati from "./logos/maserati.png";
import pagani from "./logos/pagani.png";
import pininfarina from "./logos/pininfarina.png";
import audi from "./logos/audi.png";
import bmw from "./logos/bmw.png";
import brabus from "./logos/brabus.png";
import gumpert from "./logos/gumpert.png";
import maybach from "./logos/maybach.png";
import mercedesAmg from "./logos/mercedes-amg.png";
import porsche from "./logos/porsche.png";
import arash from "./logos/arash.png";
import astonMartin from "./logos/aston-martin.png";
import bentley from "./logos/bentley.png";
import jaguar from "./logos/jaguar.png";
import lotus from "./logos/lotus.png";
import mclaren from "./logos/mclaren.png";
import radical from "./logos/radical.png";
import rollsRoyce from "./logos/rolls-royce.png";
import tvr from "./logos/tvr.png";
import alpine from "./logos/alpine.png";
import bugatti from "./logos/bugatti.png";
import chevrolet from "./logos/chevrolet.png";
import dodge from "./logos/dodge.png";
import ford from "./logos/ford.png";
import hennessey from "./logos/hennessey.png";
import mosler from "./logos/mosler.png";
import saleen from "./logos/saleen.png";
import shelby from "./logos/shelby.png";
import ssc from "./logos/ssc.png";
import koenigsegg from "./logos/koenigsegg.png";
import polestar from "./logos/polestar.png";
import rimac from "./logos/rimac.png";
import spyker from "./logos/spyker.png";
import wMotors from "./logos/w-motors.png";
import zenvo from "./logos/zenvo.png";

export const logoAssets: Record<string, string> = {
  "abarth": abarth,
  "alfa-romeo": alfaRomeo,
  "de-tomaso": deTomaso,
  "ferrari": ferrari,
  "lamborghini": lamborghini,
  "maserati": maserati,
  "pagani": pagani,
  "pininfarina": pininfarina,
  "audi": audi,
  "bmw": bmw,
  "brabus": brabus,
  "gumpert": gumpert,
  "maybach": maybach,
  "mercedes-amg": mercedesAmg,
  "porsche": porsche,
  "arash": arash,
  "aston-martin": astonMartin,
  "bentley": bentley,
  "jaguar": jaguar,
  "lotus": lotus,
  "mclaren": mclaren,
  "radical": radical,
  "rolls-royce": rollsRoyce,
  "tvr": tvr,
  "alpine": alpine,
  "bugatti": bugatti,
  "chevrolet": chevrolet,
  "dodge": dodge,
  "ford": ford,
  "hennessey": hennessey,
  "mosler": mosler,
  "saleen": saleen,
  "shelby": shelby,
  "ssc": ssc,
  "koenigsegg": koenigsegg,
  "polestar": polestar,
  "rimac": rimac,
  "spyker": spyker,
  "w-motors": wMotors,
  "zenvo": zenvo,
};
